#@ load("@ytt:data", "data")
---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample-java-app
spec:
  tag: #@ "{}/sample-java-app".format(data.values.registry_url)
  serviceAccount: kpack-builder
  builder:
    name: builder
    kind: Builder
  source:
    git:
      url: https://github.com/buildpack/sample-java-app
      revision: master
